from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
from cassandra.query import dict_factory
import json
from config import Config


class DatabaseEngine:
    def __init__(self):
        # This secure connect bundle is autogenerated when you download your SCB,
        # if yours is different update the file name below
        cloud_config = {
            'secure_connect_bundle': Config.SECURE_CONNECT_BUNDLE
        }
        # This token JSON file is autogenerated when you download your token,

        client_id = Config.CLIENT_ID
        client_secret = Config.CLIENT_SECRET

        auth_provider = PlainTextAuthProvider(client_id, client_secret)
        cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
        self.session = cluster.connect(Config.KEYSPACE)
        self.session.row_factory = dict_factory

    def exe(self, text):
        res = self.session.execute(text)
        if res:
            response = [item for item in res]
            return response

